name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-venv \
          autoconf \
          build-essential \
          libssl-dev \
          libffi-dev \
          openjdk-11-jdk \
          zip \
          unzip \
          git \
          cython3

    - name: Create virtual environment
      run: |
        python3 -m venv buildozer_venv
        source buildozer_venv/bin/activate

    - name: Install Buildozer and requirements
      run: |
        source buildozer_venv/bin/activate
        pip install --upgrade pip
        pip install buildozer
        pip install cython
        pip install python-for-android

    - name: Initialize Buildozer environment
      run: |
        source buildozer_venv/bin/activate
        # Сначала запустим команду которая скачает p4a
        buildozer android update || echo "Initial download started"
        # Даем время на скачивание
        sleep 30

    - name: Build APK (allow long timeout)
      timeout-minutes: 60
      run: |
        source buildozer_venv/bin/activate
        buildozer -v android debug

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: InkMixerPro-APK
        path: bin/*.apk
        retention-days: 5