name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-venv \
          autoconf \
          build-essential \
          libssl-dev \
          libffi-dev \
          openjdk-11-jdk \
          zip \
          unzip \
          git \
          cython3 \
          wget

    - name: Install Android Command Line Tools
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        mkdir -p ~/android-sdk/cmdline-tools
        unzip -q commandlinetools-linux-9477386_latest.zip -d ~/android-sdk/cmdline-tools
        mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
        export ANDROID_SDK_ROOT=~/android-sdk
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

    - name: Accept Android licenses and install build-tools
      run: |
        export ANDROID_SDK_ROOT=~/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Install AIDL tool (if needed)
      run: |
        # Установка AIDL через build-tools (AIDL будет внутри этого пакета)
        sdkmanager "build-tools;33.0.2"  # Убедись, что версия соответствует твоей
        echo "Checking for AIDL"
        aidl --version || echo "AIDL not found!"

    - name: Create virtual environment
      run: |
        python3 -m venv buildozer_venv
        source buildozer_venv/bin/activate

    - name: Install Buildozer and requirements
      run: |
        source buildozer_venv/bin/activate
        pip install --upgrade pip
        pip install buildozer
        pip install cython

    - name: Build APK (allow long timeout)
      timeout-minutes: 60
      run: |
        source buildozer_venv/bin/activate
        export ANDROID_SDK_ROOT=~/android-sdk
        export PATH=~/android-sdk/cmdline-tools/latest/bin:~/android-sdk/platform-tools:$PATH
        buildozer -v android debug

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: InkMixerPro-APK
        path: bin/*.apk
        retention-days: 5
